# Generated by Django 4.2.7 on 2024-03-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee.csv',
            new_name='Employee',
        ),
    ]
